//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string Year { get; set; }
        public string Rating { get; set; }
        public string Genre { get; set; }
        public string Actor { get; set; }
        public string Language { get; set; }
    }
}
